
 
package gui;

import dao.ClienteDao;
import dao.InventarioDao;
import dao.ProductoDao;
import dao.UsuarioDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Producto;

/**
 *
 * @author Luis Ramos
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    String usuarioLogueado;
    String rolUsuario;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(String nombreUsuario,String rol) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.usuarioLogueado = nombreUsuario;
        this.rolUsuario = rol;
        lblUsuarioActivo.setText("Usuario Activo: " + usuarioLogueado);
        
        bloquearPestañas();
        
        listarClientes();
        listarProductos();
        llenarComboProductos();
        listarInventario();
        mostrarUsuariosEnTabla();
        
    }

    void limpiar(){
        txtIdentidad.setText("");
        txtNombre.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
    }
    
    void limpiarProd(){
        txtNombreProducto.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
        txtCategoria.setText("");
        txtCantidad.setText("");
    }
    public void limpiarCamposUsuarios() {
    txtUsuario.setText("");
    txtContraseña.setText("");
    cbxRol.setSelectedIndex(0); // Regresa al primer rol de la lista
    txtUsuario.requestFocus();  // Pone el cursor listo para escribir de nuevo
}
    private void bloquearPestañas() {
        // Si el rol NO es Administrador (usamos ! para negar)
        if (!rolUsuario.equalsIgnoreCase("Administrador")) {
            // El número 2 corresponde a la posición de la pestaña "Usuarios"
            jTabbedPane1.setEnabledAt(2, false);

            // Opcional: puedes mandar un mensaje al log o consola
            System.out.println("Acceso restringido a Usuarios para el rol: " + rolUsuario);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        btnGuardar1 = new javax.swing.JButton();
        btnActualizar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cbxProductos = new javax.swing.JComboBox<>();
        txtCantidadActual = new javax.swing.JTextField();
        txtCantidadNueva = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnActualizarCantidad = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        cbxRol = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnGuardarUsuario = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        txtIdentidad = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnSalir2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        lblUsuarioActivo = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Menu Principal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setOpaque(false);

        tablaProductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre del Producto", "Descripcion del producto", "Precio", "Categoria", "cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nombre del producto:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Descripcion del producto: ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Precio:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Categoria:");

        txtNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreProducto.addActionListener(this::txtNombreProductoActionPerformed);

        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        txtCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCategoria.addActionListener(this::txtCategoriaActionPerformed);

        btnGuardar1.setBackground(new java.awt.Color(135, 206, 235));
        btnGuardar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar1.setText("Guardar");
        btnGuardar1.addActionListener(this::btnGuardar1ActionPerformed);

        btnActualizar1.setBackground(new java.awt.Color(135, 206, 235));
        btnActualizar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar1.setText("Actualizar");
        btnActualizar1.addActionListener(this::btnActualizar1ActionPerformed);

        btnEliminar1.setBackground(new java.awt.Color(135, 206, 235));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(this::btnEliminar1ActionPerformed);

        btnLimpiar1.setBackground(new java.awt.Color(135, 206, 235));
        btnLimpiar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.addActionListener(this::btnLimpiar1ActionPerformed);

        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(this::btnSalir1ActionPerformed);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Cantidad:");

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCantidad.addActionListener(this::txtCantidadActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGuardar1)
                        .addGap(107, 107, 107)
                        .addComponent(btnActualizar1)
                        .addGap(76, 76, 76)
                        .addComponent(btnEliminar1)
                        .addGap(79, 79, 79)
                        .addComponent(btnLimpiar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(669, 669, 669))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar1)
                    .addComponent(btnActualizar1)
                    .addComponent(btnEliminar1)
                    .addComponent(btnLimpiar1)
                    .addComponent(btnSalir1))
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Productos", jPanel2);

        jPanel3.setOpaque(false);

        cbxProductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxProductos.addItemListener(this::cbxProductosItemStateChanged);
        cbxProductos.addActionListener(this::cbxProductosActionPerformed);

        txtCantidadActual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtCantidadNueva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCantidadNueva.addActionListener(this::txtCantidadNuevaActionPerformed);

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad Actual", "Cantidad Minima", "Ultima actualizacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaInventarioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaInventario);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Productos:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Cantidad Nueva:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Cantidad actual:");

        btnActualizarCantidad.setBackground(new java.awt.Color(135, 206, 235));
        btnActualizarCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarCantidad.setText("Actualizar");
        btnActualizarCantidad.addActionListener(this::btnActualizarCantidadActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidadActual)
                            .addComponent(cbxProductos, 0, 106, Short.MAX_VALUE)
                            .addComponent(txtCantidadNueva)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnActualizarCantidad)))
                .addGap(136, 136, 136)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizarCantidad)
                .addGap(162, 162, 162))
        );

        jTabbedPane1.addTab("Inventario", jPanel3);

        jPanel4.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Usuario:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Contraseña:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Rol:");

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);

        cbxRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adminstrador", "Vendedor" }));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Usuario", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaUsuarios);

        jButton1.setBackground(new java.awt.Color(135, 206, 235));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnGuardarUsuario.setBackground(new java.awt.Color(135, 206, 235));
        btnGuardarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarUsuario.setText("Modificar");
        btnGuardarUsuario.addActionListener(this::btnGuardarUsuarioActionPerformed);

        jButton3.setBackground(new java.awt.Color(135, 206, 235));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        txtContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContraseña.addActionListener(this::txtContraseñaActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 166, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario)
                            .addComponent(txtContraseña))
                        .addGap(97, 97, 97)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addGap(116, 116, 116)
                .addComponent(btnGuardarUsuario)
                .addGap(111, 111, 111)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnGuardarUsuario)
                    .addComponent(jButton3))
                .addGap(57, 57, 57))
        );

        jTabbedPane1.addTab("Usuarios", jPanel4);

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));
        jPanel1.setOpaque(false);

        txtIdentidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreo.addActionListener(this::txtCorreoActionPerformed);

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.addActionListener(this::txtNombreActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Identidad:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Telefono:");

        tablaClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Identidad", "Nombre", "Telefono", "Correo", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaClientes.setOpaque(false);
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaClientes);

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Direccion:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Correo:");

        btnGuardar.setBackground(new java.awt.Color(135, 206, 235));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnLimpiar.setBackground(new java.awt.Color(135, 206, 235));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(135, 206, 235));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnActualizar.setBackground(new java.awt.Color(135, 206, 235));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnGuardar)
                                .addGap(107, 107, 107)
                                .addComponent(btnActualizar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnEliminar)
                        .addGap(97, 97, 97)
                        .addComponent(btnLimpiar)
                        .addContainerGap(421, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addGap(145, 145, 145))
        );

        jTabbedPane1.addTab("Clientes", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 1267, -1));

        btnSalir2.setBackground(new java.awt.Color(135, 206, 235));
        btnSalir2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir2.setText("Cerrar sesion");
        btnSalir2.addActionListener(this::btnSalir2ActionPerformed);
        getContentPane().add(btnSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 760, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/logotipoOriginal.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 147));

        lblUsuarioActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioActivo.setText(" ");
        getContentPane().add(lblUsuarioActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 30, 191, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/FondoMenu.png"))); // NOI18N
        jLabel19.setText("jLabel19");
        jLabel19.setToolTipText("");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1670, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void listarClientes() {
    ClienteDao dao = new ClienteDao();
    List<Cliente> lista = dao.listar();
    
    // Obtenemos el modelo de la tabla que diseñaste
    DefaultTableModel modeloTabla = (DefaultTableModel) tablaClientes.getModel();
    
    // Limpiamos la tabla por si ya tenía datos viejos
    modeloTabla.setRowCount(0);
    
    // Creamos un array de objetos para cada fila (basado en tus 5 campos)
    Object[] fila = new Object[6]; 
    for (int i = 0; i < lista.size(); i++) {
        fila[0] = lista.get(i).getId_cliente();
        fila[1] = lista.get(i).getIdentidad();
        fila[2] = lista.get(i).getNombre_completo();
        fila[3] = lista.get(i).getTelefono();
        fila[4] = lista.get(i).getCorreo();
        fila[5] = lista.get(i).getDireccion();
        
        modeloTabla.addRow(fila);
    }
    // Asignamos el modelo actualizado a la tabla
    tablaClientes.setModel(modeloTabla);
}
    public void listarProductos() {
        ProductoDao dao = new ProductoDao();
        List<Producto> lista = dao.listar();
        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0);

        Object[] fila = new Object[6]; // ID, Nombre, Precio, Categoría
        for (int i = 0; i < lista.size(); i++) {
            fila[0] = lista.get(i).getId_producto();
            fila[1] = lista.get(i).getNombre();
            fila[2] = lista.get(i).getDescripcion();
            fila[3] = lista.get(i).getPrecio();
            fila[4] = lista.get(i).getCategoria();
            fila[5] = lista.get(i).getCantidad();
            modelo.addRow(fila);
        }
        tablaProductos.setModel(modelo);
    }
    
    public void listarInventario() {
        // Usamos el InventarioDao que creamos
        InventarioDao invDao = new InventarioDao();
        List<Object[]> lista = invDao.listarInventarioCompleto(); // El método que une Productos e Inventario
        DefaultTableModel modeloInv = (DefaultTableModel) tablaInventario.getModel();
        modeloInv.setRowCount(0); // Limpiar tabla
        for (Object[] fila : lista) {
            modeloInv.addRow(fila);
        }
    }
    public void mostrarUsuariosEnTabla() {
        UsuarioDao dao = new UsuarioDao();
        List<Object[]> lista = dao.listarUsuarios();
        DefaultTableModel modelo = (DefaultTableModel) tablaUsuarios.getModel();

        modelo.setRowCount(0); // Limpia la tabla antes de cargarla

        for (Object[] fila : lista) {
            modelo.addRow(fila);
        }
    }
    
    public void llenarComboProductos() {
        ProductoDao dao = new ProductoDao();
        List<Producto> lista = dao.listar();
        cbxProductos.removeAllItems(); // Limpiamos para no repetir
        for (int i = 0; i < lista.size(); i++) {
            cbxProductos.addItem(lista.get(i).getNombre());
        }
    }
    
    private String valorCelda(int fila, int columna) {
        Object valor = tablaClientes.getValueAt(fila, columna);
        return (valor != null) ? valor.toString() : "";
    }
    
    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Está seguro de que desea cerrar sesión?",
                "Cerrar Sesión",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (respuesta == JOptionPane.YES_OPTION) {
            // 2. Crear una instancia de tu ventana de Login
            // Reemplaza 'LoginV' por el nombre exacto de tu clase de Login
            InicioSesion ventanaLogin = new InicioSesion();

            // 3. Hacer visible el Login
            ventanaLogin.setVisible(true);

            // 4. Cerrar (destruir) la ventana actual del Menú Principal
            this.dispose();
        }
    }//GEN-LAST:event_btnSalir2ActionPerformed
    
    int idUsuarioSeleccionado;
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        int fila = tablaClientes.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente de la tabla para actualizar");
        } else {
            Cliente cl = new Cliente();
            ClienteDao dao = new ClienteDao();

            // 1. Capturamos el ID de la fila seleccionada (columna 0)
            int id = Integer.parseInt(tablaClientes.getValueAt(fila, 0).toString());

            // 2. Llenamos el objeto con los datos de los JTextFields
            cl.setId_cliente(id);
            cl.setIdentidad(txtIdentidad.getText());
            cl.setNombre_completo(txtNombre.getText());
            cl.setCorreo(txtCorreo.getText());
            cl.setTelefono(txtTelefono.getText());
            cl.setDireccion(txtDireccion.getText());

            // 3. Ejecutamos la actualización
            if (dao.actualizar(cl)) {
                JOptionPane.showMessageDialog(this, "Cliente actualizado con éxito");
                listarClientes(); // Para que los cambios se vean en la tabla
                limpiar();  // (Opcional) Para vaciar los textos
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar");
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tablaClientes.getSelectedRow();

        // 2. Verificar si el usuario seleccionó algo
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila de la tabla");
        } else {
            // 3. Confirmar la eliminación
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este cliente?", "Confirmar", JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {
                // 4. Obtener el ID de la primera columna (columna 0)
                int id = Integer.parseInt(tablaClientes.getValueAt(fila, 0).toString());

                // 5. Llamar al DAO para borrar
                ClienteDao dao = new ClienteDao();
                dao.eliminar(id);

                // 6. Actualizar la tabla y limpiar campos
                listarClientes();
                JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Cliente cl = new Cliente();
        ClienteDao dao = new ClienteDao();

        // 1. Validar que los campos no estén vacíos
        if (!txtIdentidad.getText().isEmpty() && !txtNombre.getText().isEmpty()) {

            // 2. Llenar el objeto Cliente con lo que escribió el usuario
            cl.setIdentidad(txtIdentidad.getText());
            cl.setNombre_completo(txtNombre.getText());
            cl.setCorreo(txtCorreo.getText());
            cl.setTelefono(txtTelefono.getText());
            cl.setDireccion(txtDireccion.getText());

            // 3. Llamar al DAO para guardar en MySQL
            if (dao.agregar(cl) == 1) {
                JOptionPane.showMessageDialog(null, "Cliente guardado con éxito");
                listarClientes();
                limpiar();
                // Aquí podrías llamar a un método para limpiar los campos
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar cliente");
            }
        } else {
            JOptionPane.showMessageDialog(null, "La identidad y el nombre son obligatorios");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        // TODO add your handling code here:
        int fila = tablaClientes.getSelectedRow();
        if (fila != -1) {

            txtIdentidad.setText(valorCelda(fila, 1));
            txtNombre.setText(valorCelda(fila, 2));
            txtTelefono.setText(valorCelda(fila, 3));
            txtCorreo.setText(valorCelda(fila, 4));
            txtDireccion.setText(valorCelda(fila, 5));

        }
    }//GEN-LAST:event_tablaClientesMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (idUsuarioSeleccionado == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario de la tabla para eliminar");
        } else {
            // 2. Preguntar antes de borrar (Buena práctica)
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar a este usuario?",
                "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {
                UsuarioDao dao = new UsuarioDao();

                // 3. Llamamos al método pasándole solo el ID
                if (dao.eliminarUsuario(idUsuarioSeleccionado)) {
                    JOptionPane.showMessageDialog(null, "Usuario eliminado correctamente");

                    mostrarUsuariosEnTabla();
                    limpiarCamposUsuarios();
                    idUsuarioSeleccionado = 0;
                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar el usuario");
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnGuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUsuarioActionPerformed
        // TODO add your handling code here:
        if (txtUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario de la tabla");
        } else {
            String user = txtUsuario.getText();
            String pass;
            pass = String.valueOf(txtContraseña.getPassword());
            String rol = cbxRol.getSelectedItem().toString();

            UsuarioDao dao = new UsuarioDao();
            if (dao.modificarUsuario(idUsuarioSeleccionado,user, pass, rol)) {
                JOptionPane.showMessageDialog(null, "Usuario actualizado correctamente");
                mostrarUsuariosEnTabla(); // Refresca la tabla
                limpiarCamposUsuarios();  // Limpia los textos
            } else {
                JOptionPane.showMessageDialog(null, "Error al modificar");
            }
        }
    }//GEN-LAST:event_btnGuardarUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user = txtUsuario.getText();
        String pass = String.valueOf(txtContraseña.getPassword()); // Para JPasswordField
        String rol = cbxRol.getSelectedItem().toString();

        // 2. Validación básica: que no estén vacíos
        if (user.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
        } else {
            UsuarioDao dao = new UsuarioDao();

            // 3. Llamamos al método y verificamos el éxito
            if (dao.agregarUsuario(user, pass, rol)) {
                JOptionPane.showMessageDialog(null, "¡Usuario creado exitosamente!");
                limpiarCamposUsuarios(); // Crea un método para vaciar los cuadros de texto
                mostrarUsuariosEnTabla();        // Refresca la tabla que tienes a la derecha
            } else {
                JOptionPane.showMessageDialog(null, "Error: El nombre de usuario ya existe");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
        int fila = tablaUsuarios.getSelectedRow();
        // Guardamos el ID de la columna 0 en nuestra variable
        idUsuarioSeleccionado = Integer.parseInt(tablaUsuarios.getValueAt(fila, 0).toString());

        // Llenamos los textos con las otras columnas
        txtUsuario.setText(tablaUsuarios.getValueAt(fila, 1).toString());
        cbxRol.setSelectedItem(tablaUsuarios.getValueAt(fila, 2).toString());
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnActualizarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCantidadActionPerformed
        try {
            // 1. Validaciones básicas
            if (txtCantidadNueva.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese la cantidad que desea sumar.");
                return;
            }

            // 2. Obtener datos de los componentes
            String nombreProd = cbxProductos.getSelectedItem().toString(); //
            int cantidadEntrante = Integer.parseInt(txtCantidadNueva.getText());

            ProductoDao prodDao = new ProductoDao();
            InventarioDao invDao = new InventarioDao();

            // 3. Obtener stock actual (esto devuelve un int, no un Producto)
            int stockAnterior = prodDao.obtenerCantidadPorNombre(nombreProd);

            // 4. Calcular el total
            int stockFinal = stockAnterior + cantidadEntrante;

            // 5. Buscar el ID para poder actualizar la tabla inventario
            // Recorremos la lista para encontrar el ID del producto seleccionado
            java.util.List<modelo.Producto> lista = prodDao.listar();
            int idEncontrado = 0;
            for (modelo.Producto item : lista) {
                if (item.getNombre().equals(nombreProd)) {
                    idEncontrado = item.getId_producto();
                    break;
                }
            }

            // 6. Guardar en la base de datos
            if (invDao.actualizarStock(stockFinal, idEncontrado)) {
                JOptionPane.showMessageDialog(null, "¡Stock actualizado!\nTotal en bodega: " + stockFinal);

                listarProductos();
                listarInventario();
                // Actualizar cuadros de texto
                txtCantidadActual.setText(String.valueOf(stockFinal));
                txtCantidadNueva.setText("");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Ingrese solo números en la cantidad.");
        }
    }//GEN-LAST:event_btnActualizarCantidadActionPerformed

    private void txtCantidadNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadNuevaActionPerformed

    private void cbxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxProductosActionPerformed

    private void cbxProductosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProductosItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            try {
                String nombreProd = cbxProductos.getSelectedItem().toString();

                // Si el combo está vacío por alguna razón, no hagas nada
                if (nombreProd.equals("Seleccionar") || nombreProd.isEmpty()) {
                    return;
                }

                ProductoDao prodDao = new ProductoDao();
                int stockEncontrado = prodDao.obtenerCantidadPorNombre(nombreProd);

                txtCantidadActual.setText(String.valueOf(stockEncontrado));

            } catch (Exception e) {
                System.out.println("Error al cambiar de producto: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_cbxProductosItemStateChanged

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        // TODO add your handling code here:
        limpiarProd();
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        int fila = tablaProductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto");
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro de eliminar este producto?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                int id = Integer.parseInt(tablaProductos.getValueAt(fila, 0).toString());
                ProductoDao dao = new ProductoDao();
                if (dao.eliminar(id)) {
                    JOptionPane.showMessageDialog(this, "Producto eliminado");
                    listarProductos();
                    limpiarProd();
                }
            }
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        // TODO add your handling code here:
        int fila = tablaProductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla");
        } else {
            Producto p = new Producto();
            ProductoDao dao = new ProductoDao();

            int id = Integer.parseInt(tablaProductos.getValueAt(fila, 0).toString());
            p.setId_producto(id);
            p.setNombre(txtNombreProducto.getText());
            p.setDescripcion(txtDescripcion.getText());
            p.setPrecio(Double.parseDouble(txtPrecio.getText()));
            p.setCategoria(txtCategoria.getText());
            p.setCantidad(Integer.parseInt(txtCantidad.getText()));

            if (dao.actualizar(p)) {
                JOptionPane.showMessageDialog(this, "Producto actualizado correctamente");
                listarProductos();
                limpiarProd();
            }
        }
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
        Producto p = new Producto();
        ProductoDao dao = new ProductoDao();

        if (!txtNombreProducto.getText().isEmpty() && !txtPrecio.getText().isEmpty()) {
            try {
                p.setNombre(txtNombreProducto.getText());
                p.setDescripcion(txtDescripcion.getText());
                p.setPrecio(Double.parseDouble(txtPrecio.getText()));
                p.setCategoria(txtCategoria.getText());
                p.setCantidad(Integer.parseInt(txtCantidad.getText()));

                if (dao.agregar(p)==1) {
                    JOptionPane.showMessageDialog(this, "Producto registrado con éxito");
                    listarProductos();
                    listarInventario();// Refresca la tabla
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar producto");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El precio debe ser un número entero");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nombre y Precio son obligatorios");
        }
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        // TODO add your handling code here:
        int fila = tablaProductos.getSelectedRow();
        if (fila != -1) {
            txtNombreProducto.setText(tablaProductos.getValueAt(fila, 1).toString());
            txtDescripcion.setText(tablaProductos.getValueAt(fila,2).toString());
            txtPrecio.setText(tablaProductos.getValueAt(fila, 3).toString());
            txtCategoria.setText(tablaProductos.getValueAt(fila, 4).toString());
            txtCantidad.setText(tablaProductos.getValueAt(fila, 5).toString());
        }
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void tablaInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInventarioMouseClicked
        // TODO add your handling code here:
        int fila = tablaInventario.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        } else {
            // Obtenemos los datos de las columnas de la tabla
            // Ajusta el índice (0, 1, 2...) según el orden de tus columnas
            String nombreProd = tablaInventario.getValueAt(fila, 1).toString();
            String stockActual = tablaInventario.getValueAt(fila, 2).toString();

            // Los pasamos a los campos de texto
            cbxProductos.setSelectedItem(nombreProd); // O el nombre de tu campo
            txtCantidadActual.setText(stockActual);

            // Es buena práctica poner el foco en el campo de "Cantidad Nueva"
            txtCantidadNueva.requestFocus();
        }
    }//GEN-LAST:event_tablaInventarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Agregamos dos textos de prueba entre comillas
            // Esto solo sirve para que el error desaparezca y puedas darle "Run"
            new MenuPrincipal("Usuario", "Rol").setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnActualizarCantidad;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnGuardarUsuario;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JComboBox<String> cbxProductos;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblUsuarioActivo;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadActual;
    private javax.swing.JTextField txtCantidadNueva;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
